# ownCloud with MariaDB/MySQL
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: see env file
# Database name: pick any name
# Database host: replace "localhost" with "mysql"

version: '2'
services:
  owncloud:
    image: owncloud
    volumes:
      - "${DISK_ROOT}/cloud:/var/www/html"
    ports:
      - "127.0.0.1:${PORT_CLOUD}:80"
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${CLOUD_MYSQL_PASSWORD}
