#!/bin/sh

# Vider les tables actuelles
iptables -t filter -F INPUT
iptables -t filter -F OUTPUT

# Vider les règles personnelles
#iptables -t filter -X

# Interdire toute connexion entrante et sortante
iptables -t filter -P INPUT DROP
#iptables -t filter -P FORWARD DROP
iptables -t filter -P OUTPUT ACCEPT

# ---

# Ne pas casser les connexions etablies
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

# Autoriser loopback
iptables -t filter -A INPUT -i lo -j ACCEPT
iptables -t filter -A OUTPUT -o lo -j ACCEPT

# ICMP (Ping)
iptables -t filter -A INPUT -p icmp --icmp-type any -j ACCEPT
iptables -t filter -A OUTPUT -p icmp --icmp-type any -j ACCEPT

# Local-bound public services (does not cover docker-exposed ports)
iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 8080 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 9010 -j ACCEPT # MQTT
iptables -t filter -A INPUT -p tcp -s 172.17.0.0/16 --dport 9123 -j ACCEPT # MQTT private

# VPN
iptables -t filter -A INPUT -p udp --dport 1194 -j ACCEPT


# Fail2Ban


# Unlink from INPUT and FORWARD
iptables -t filter -D INPUT -j fail2ban-jails
iptables -t filter -D FORWARD -j fail2ban-jails

# Make sure it's deleted
#iptables -t filter -F fail2ban-jails
#iptables -t filter -X fail2ban-jails

# Create fail2ban chain
iptables -t filter -N fail2ban-jails
# Add the default rule making sure there's no duplicate
iptables -t filter -D fail2ban-jails -j RETURN
iptables -t filter -A fail2ban-jails -j RETURN

# Link fail2ban chain to both INPUT and FORWARD
iptables -t filter -I INPUT -j fail2ban-jails
iptables -t filter -I FORWARD -j fail2ban-jails

# To add a jail:
# iptables -t filter -I fail2ban-jails -j <my-jail> -p <tcp|udp> --dport <port>

