version: '2'
services:
  slave0:
    image: jenkinsci/jnlp-slave
    environment:
      - JENKINS_URL=http://master:8080
      - JENKINS_SECRET=${JENKINS_SLAVE0_SECRET}
      - JENKINS_AGENT_NAME=docker01
    restart: always
    links:
      - master
  ansible:
    build: ansible-slave
    environment:
      - JENKINS_URL=http://master:8080
      - JENKINS_SECRET=${JENKINS_SLAVE_ANSIBLE_SECRET}
      - JENKINS_AGENT_NAME=ansible
    restart: always
    volumes:
      - "${VPS_HOME}/services/jenkins/ssh-keys/master:/home/jenkins/.ssh"
    links:
      - master
      - audiweb
  audiweb:
    build: ansible-target
    volumes:
      - "${VPS_HOME}/services/jenkins/ssh-keys/slave:/root/.ssh"
    restart: always
  master:
    image: jenkinsci/jenkins:lts
    volumes:
      - "${DISK_ROOT}/jenkins:/var/jenkins_home"
    ports:
      - "127.0.0.1:${PORT_JENKINS}:8080"
    restart: always
#    environment:
#      - "JAVA_OPTS=-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
#    links:
#      - audiweb
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://127.0.0.1:514"
#        tag: jenkins

