version: '2'
services:
  audiweb:
    build: audiweb
    environment:
      - JENKINS_URL=http://master:8080
      - JENKINS_SECRET=${JENKINS_AUDIWEB_SECRET}
      - JENKINS_AGENT_NAME=audiweb
    restart: always
    links:
      - master
    volumes:
      # DISK storage is slow af so we run build stuff on the SSD
      - "${RUNTIME_ROOT}/audiweb:/home/jenkins"
      - "${DISK_ROOT}/audiweb:/var/dist"
  master:
    image: jenkinsci/jenkins:lts
    volumes:
      - "${DISK_ROOT}/jenkins:/var/jenkins_home"
    ports:
      - "127.0.0.1:${PORT_JENKINS}:8080"
    restart: always
#    environment:
#      - "JAVA_OPTS=-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
#    links:
#      - audiweb
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://127.0.0.1:514"
#        tag: jenkins

