version: '2'
services:
  web:
    image: nginx:latest
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ${DISK_ROOT}/cert:/var/cert
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
      - travel_default
networks:
  travel_default:
    external: true
